version: '3.1'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: /home/ubuntu/project/projectenv/bin/gunicorn --workers 3 --bind unix:project.sock -m 007 wsgi:app
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - project

networks:
  my-network: